# Site settings
title: RUFTEX
email: hello@sufnitextil.eu
description-en: Professional sewing services.
description-hu: Profi varrodai szolgáltatások.
mailing-en: Bérvarrás sportruházattól lakástextilekig.
mailing-hu: Sewing contractor for sportswear, hometextiles and many more.
catalog-en: Get in touch for more information.
catalog-hu: További információért lépjen velünk kapcsolatba.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://ruftex.eu" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: "http://facebook.com/Ruftex-137042636884949/"
github_url:
gitlab_url:
googleplus_url:
instagram_url: "https://www.instagram.com/ruftexworkwear/"
linkedin_url:
pinterest_url:
slack_url:
twitter_url: "https://twitter.com/ruftexworkwear"

# Build settings
markdown: kramdown

# Logo settings
logo-image-url: assets/images/logo.svg
