# Site settings
title: RUFTEX
email: hello@sufnitextil.eu
description-en: Workwear for ROUGH environments.
description-hu: Munkaruha a KEMÉNY helyekre.
mailing-en: Get in touch for more information.
mailing-hu: További információért lépjen velünk kapcsolatba.
catalog-en: Our <a href="http://ruftex.eu/ruftex-final.html">catalog</a> is available online and in <a href="http://ruftex.eu/assets/ruftex-final.pdf">pdf</a> format.
catalog-hu: <a href="http://ruftex.eu/ruftex-final.html">Katalógusunk</a> elérhető online és letölthető <a href="http://ruftex.eu/assets/ruftex-final.pdf">pdf</a> formátumban.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://ruftex.eu" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: "http://facebook.com/Ruftex-137042636884949/"
github_url:
gitlab_url:
googleplus_url:
instagram_url: "https://www.instagram.com/ruftexworkwear/"
linkedin_url:
pinterest_url:
slack_url:
twitter_url: "https://twitter.com/ruftexworkwear"

# Build settings
markdown: kramdown

# Logo settings
logo-image-url: assets/images/logo.svg
