# Site settings
title: RUFTEX
email: hello@sufnitextil.eu
description-en: Workwear for ROUGH environments.
mailing-en: Sign up for our mailinglist and receive updates about our launch date.
baseurl: "/ruftex" # the subpath of your site, e.g. /blog
url: "https://vestalux.github.io" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

# Logo settings
logo-image-url: assets/images/logo.svg